DROP TABLE IF EXISTS `schiepph`.`syndromic_surveillance_data`;
CREATE TABLE  `schiepph`.`syndromic_surveillance_data` (
  `facility_identifier` varchar(50) NOT NULL DEFAULT '',
  `facility_location_street` varchar(50) DEFAULT NULL,
  `facility_location_city` varchar(50) DEFAULT NULL,
  `facility_location_county` varchar(50) DEFAULT NULL,
  `facility_location_state` varchar(50) DEFAULT NULL,
  `facility_visit_type` varchar(50) DEFAULT NULL,
  `facility_name` varchar(50) DEFAULT NULL,
  `report_date_time` varchar(50) NOT NULL DEFAULT '',
  `unique_patient_id` varchar(50) NOT NULL DEFAULT '',
  `medical_record_number` varchar(50) DEFAULT NULL,
  `age` varchar(50) DEFAULT NULL,
  `age_units` varchar(50) DEFAULT NULL,
  `gender` varchar(50) DEFAULT NULL,
  `city_town` varchar(50) DEFAULT NULL,
  `zip_code` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `race` varchar(50) DEFAULT NULL,
  `ethnicity` varchar(50) DEFAULT NULL,
  `county` varchar(50) DEFAULT NULL,
  `unique_visiting_id` varchar(100) DEFAULT NULL,
  `visit_date_time` varchar(50) DEFAULT NULL,
  `date_of_onset` varchar(50) DEFAULT NULL,
  `patient_class` varchar(50) DEFAULT NULL,
  `chief_complaint_reason_for_visit` varchar(2000) DEFAULT NULL,
  `triage_notes` varchar(2000) DEFAULT NULL,
  `diagnosis_injury_code` varchar(50) DEFAULT NULL,
  `clinical_impression` varchar(50) DEFAULT NULL,
  `diagnosis_type` varchar(50) DEFAULT NULL,
  `discharge_disposition` varchar(100) DEFAULT NULL,
  `disposition_date_time` varchar(50) DEFAULT NULL,
  `initial_temperature` varchar(50) DEFAULT NULL,
  `temperature_units` varchar(50) DEFAULT NULL,
  `initial_pulse_oximetry` varchar(50) DEFAULT NULL,
  `pulse_oximetry_units` varchar(50) DEFAULT NULL,
  `processed_flag` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`facility_identifier`,`unique_patient_id`,`report_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
